services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8000:8000"
      - "9000:9000"
      - "6001:6001"

  web:
    image: nginx:alpine
    networks:
      - app-network

  db:
    image: mysql:8.0.32
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
